"""add_aadhaar_verification

Revision ID: 427efe237a1b
Revises: 7a014679d81c
Create Date: 2026-07-21 15:11:13.146033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427efe237a1b'
down_revision: Union[str, None] = '7a014679d81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aadhaar_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.String(length=100), nullable=False),
    sa.Column('aadhaar_number_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aadhaar_verifications_aadhaar_number_hash'), 'aadhaar_verifications', ['aadhaar_number_hash'], unique=False)
    op.create_index(op.f('ix_aadhaar_verifications_id'), 'aadhaar_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_aadhaar_verifications_ref_id'), 'aadhaar_verifications', ['ref_id'], unique=True)
    op.create_index(op.f('ix_aadhaar_verifications_user_id'), 'aadhaar_verifications', ['user_id'], unique=False)
    op.add_column('profiles', sa.Column('is_aadhaar_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('profiles', sa.Column('aadhaar_name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'aadhaar_name')
    op.drop_column('profiles', 'is_aadhaar_verified')
    op.drop_index(op.f('ix_aadhaar_verifications_user_id'), table_name='aadhaar_verifications')
    op.drop_index(op.f('ix_aadhaar_verifications_ref_id'), table_name='aadhaar_verifications')
    op.drop_index(op.f('ix_aadhaar_verifications_id'), table_name='aadhaar_verifications')
    op.drop_index(op.f('ix_aadhaar_verifications_aadhaar_number_hash'), table_name='aadhaar_verifications')
    op.drop_table('aadhaar_verifications')
    # ### end Alembic commands ###
