"""add_ai_routing_fields

Revision ID: 439935176dcb
Revises: 966f874d4ce3
Create Date: 2026-08-06 10:16:03.654675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439935176dcb'
down_revision: Union[str, None] = '966f874d4ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('ai_issue_type', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('ai_reasoning', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('ai_image_agreement', sa.String(length=50), nullable=True))
    op.add_column('complaints', sa.Column('ai_routing_status', sa.String(length=50), server_default='PENDING', nullable=True))
    op.create_index(op.f('ix_complaints_ai_routing_status'), 'complaints', ['ai_routing_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_ai_routing_status'), table_name='complaints')
    op.drop_column('complaints', 'ai_routing_status')
    op.drop_column('complaints', 'ai_image_agreement')
    op.drop_column('complaints', 'ai_reasoning')
    op.drop_column('complaints', 'ai_confidence')
    op.drop_column('complaints', 'ai_issue_type')
    # ### end Alembic commands ###
