"""create_unified_worker_profiles

Revision ID: 484bffd656e4
Revises: dc358ce2beff
Create Date: 2026-07-18 09:13:20.078879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484bffd656e4'
down_revision: Union[str, None] = 'dc358ce2beff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('place', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('skill', sa.String(length=100), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('joining_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('availability', sa.String(length=30), nullable=False),
    sa.Column('employment_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_worker_profiles_department'), 'worker_profiles', ['department'], unique=False)
    op.create_index(op.f('ix_worker_profiles_manager_id'), 'worker_profiles', ['manager_id'], unique=False)
    op.create_index(op.f('ix_worker_profiles_user_id'), 'worker_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_profiles_user_id'), table_name='worker_profiles')
    op.drop_index(op.f('ix_worker_profiles_manager_id'), table_name='worker_profiles')
    op.drop_index(op.f('ix_worker_profiles_department'), table_name='worker_profiles')
    op.drop_table('worker_profiles')
    # ### end Alembic commands ###
