"""add status_updated_at

Revision ID: 966f874d4ce3
Revises: edd37758a6f5
Create Date: 2026-07-31 06:39:03.180221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966f874d4ce3'
down_revision: Union[str, None] = 'edd37758a6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffic_worker_profiles', sa.Column('status_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('worker_profiles', sa.Column('status_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_profiles', 'status_updated_at')
    op.drop_column('traffic_worker_profiles', 'status_updated_at')
    # ### end Alembic commands ###
